"""added foreign key to user in meme model

Revision ID: ed28f1872cfa
Revises: 459aa7730308
Create Date: 2024-07-15 22:14:02.431989

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ed28f1872cfa'
down_revision: Union[str, None] = '459aa7730308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'memes', 'users', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memes', type_='foreignkey')
    op.drop_column('memes', 'author')
    # ### end Alembic commands ###
